# Test Trigger

trigger: none

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export ADO_ORG=cloudnativenow; echo $ADO_ORG
      export ADO_PROJECT=contosoairlines; echo $ADO_PROJECT
      export ADO_PID=4; echo $ADO_PID
      export ADO_PAT=kdc2dkdgqjy7iwdy56245sl2mh7r7z7mmcyh3l3oixu564neoboa; echo $ADO_PAT
      export ADO_URL="https://dev.azure.com/$ADO_ORG/$ADO_PROJECT/_apis/pipelines/$ADO_PID/runs?api-version=6.0"; echo $ADO_URL
      curl -X POST -H 'Content-Type: application/json' -H 'Content-Length:0' $ADO_URL --user '':$ADO_PAT